package com.example.wxnotion.util;

import lombok.extern.slf4j.Slf4j;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.UUID;

/**
 * 每日日签图片生成器
 * 用于生成包含金句、关键词的高颜值图片，方便用户分享朋友圈
 */
@Slf4j
public class ImageGenerator {

    private static final int WIDTH = 800;
    private static final int HEIGHT = 1000;
    private static final int PADDING = 60;
    // 临时文件目录
    private static final String TEMP_DIR = System.getProperty("java.io.tmpdir");

    /**
     * 生成日签图片
     * @param quote 金句 (AI 总结的核心句子)
     * @param keywords 关键词 (如 #生活 #记录)
     * @return 生成的图片文件路径
     */
    public static File generateDailyCard(String quote, String keywords) throws IOException {
        BufferedImage image = new BufferedImage(WIDTH, HEIGHT, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = image.createGraphics();

        // 1. 设置抗锯齿，让文字丝般顺滑
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        // 2. 绘制背景 (米白色，更有纸质感)
        g2.setColor(new Color(250, 249, 246)); 
        g2.fillRect(0, 0, WIDTH, HEIGHT);

        // 3. 绘制顶部日期
        g2.setColor(new Color(50, 50, 50));
        g2.setFont(new Font("Serif", Font.BOLD, 48));
        String dateStr = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy.MM.dd"));
        g2.drawString(dateStr, PADDING, 120);
        
        g2.setFont(new Font("Serif", Font.PLAIN, 24));
        String weekStr = LocalDate.now().getDayOfWeek().toString();
        g2.drawString(weekStr, PADDING, 160);

        // 4. 绘制分割线
        g2.setColor(new Color(200, 200, 200));
        g2.drawLine(PADDING, 200, WIDTH - PADDING, 200);

        // 5. 绘制金句 (核心内容)
        g2.setColor(new Color(30, 30, 30));
        // 使用无衬线字体，更现代
        Font quoteFont = new Font("SansSerif", Font.PLAIN, 36);
        g2.setFont(quoteFont);
        
        int currentY = 300;
        currentY = drawWrappedText(g2, quote, PADDING, currentY, WIDTH - 2 * PADDING, 60);

        // 6. 绘制关键词 (底部)
        g2.setColor(new Color(100, 100, 150)); // 淡蓝色
        g2.setFont(new Font("SansSerif", Font.ITALIC, 28));
        g2.drawString(keywords, PADDING, HEIGHT - 150);

        // 7. 底部品牌落款
        g2.setColor(new Color(150, 150, 150));
        g2.setFont(new Font("SansSerif", Font.PLAIN, 20));
        g2.drawString("Generated by Inspiration Seconds", PADDING, HEIGHT - 60);

        g2.dispose();

        // 保存文件
        File file = new File(TEMP_DIR, "daily_card_" + UUID.randomUUID() + ".jpg");
        ImageIO.write(image, "jpg", file);
        log.info("日签图片已生成: {}", file.getAbsolutePath());
        return file;
    }

    /**
     * 绘制自动换行的文本
     */
    private static int drawWrappedText(Graphics2D g2, String text, int x, int y, int maxWidth, int lineHeight) {
        FontMetrics fm = g2.getFontMetrics();
        String[] words = text.split(""); // 按字符分割 (简单处理中文)
        StringBuilder line = new StringBuilder();
        int curY = y;

        for (String word : words) {
            if (fm.stringWidth(line + word) < maxWidth) {
                line.append(word);
            } else {
                g2.drawString(line.toString(), x, curY);
                line = new StringBuilder(word);
                curY += lineHeight;
            }
        }
        if (line.length() > 0) {
            g2.drawString(line.toString(), x, curY);
        }
        return curY + lineHeight;
    }
}
